CREATE TABLE [dbo].[ECI_TABLE_ELEMENT] (
    [CODE]                   VARCHAR (200)  NULL,
    [MAIN_ALIAS]             VARCHAR (400)  NULL,
    [PHYSICAL_TYPE]          VARCHAR (200)  NULL,
    [FIELD_LENGTH]           INT            NULL,
    [WIDTH]                  INT            NULL,
    [LINK_URL]               VARCHAR (2000) NULL,
    [SQL_ATTRIBUTE]          VARCHAR (2000) NULL,
    [TABLE_GUID]             VARCHAR (72)   NULL,
    [DEFAULT_VALUE]          VARCHAR (200)  NULL,
    [DICTIONARY_TYPE]        VARCHAR (400)  NULL,
    [GRID_SHOW]              INT            NULL,
    [EDIT_SHOW]              INT            NULL,
    [QUERY_SHOW]             INT            NULL,
    [GUID]                   VARCHAR (72)   NOT NULL,
    [PRIMARY_KEY]            INT            NULL,
    [NULLABLE_KEY]           INT            NULL,
    [UNIQUE_KEY]             INT            NULL,
    [DICTIONARY_TYPE_CONFIG] VARCHAR (400)  NULL,
    [QUERY_SEQ]              INT            NULL,
    [EDIT_SEQ]               INT            NULL,
    [EDIT_LOCK_MODE]         VARCHAR (40)   NULL,
    [SYSTEM_DATA]            VARCHAR (200)  NULL,
    [SYSTEM_DATA_TRIGGER]    VARCHAR (200)  NULL,
    [CREATE_DATE]            DATETIME       NULL,
    [COLSPAN]                INT            NULL,
    [SHOW_CONVERT]           VARCHAR (200)  NULL,
    [PRIMARY_CREATOR]        VARCHAR (200)  NULL,
    [COPY_REMOVE_DATA]       INT            NULL,
    [QUERY_ADD_EMPTY]        INT            NULL,
    [GROUP_CODE]             VARCHAR (40)   NULL,
    [EDIT_HIDE_LABEL]        INT            NULL,
    [GRID_SEQ]               INT            NULL,
    [CSS]                    VARCHAR (40)   NULL,
    [WRAP]                   VARCHAR (1)    NULL,
    [CONTROL_WIDTH]          VARCHAR (200)  NULL,
    [NOT_SAVE]               VARCHAR (1)    NULL,
    [DEFAULT_VALUE_QUERY]    VARCHAR (100)  NULL,
    [HIDDEN]                 VARCHAR (1)    NULL,
    [DB_FIELD]               VARCHAR (100)  NULL,
    [DATA_FORMAT_GRID]       VARCHAR (100)  NULL,
    [DATA_SOURCE]            VARCHAR (100)  NULL,
    [GRID_HEAD_ALIGN]        VARCHAR (20)   NULL,
    [GRID_ITEM_ALIGN]        VARCHAR (20)   NULL,
    [SHOW_TIP]               VARCHAR (1)    NULL,
    [SQL_ATTRIBUTE_EX]       VARCHAR (400)  NULL,
    [CONTRACT_TEXT]          VARCHAR (400)  NULL,
    [TO_DBC]                 VARCHAR (400)  NULL,
    [EDIT_TIP]               VARCHAR (2000) NULL,
    [DATA_FORMAT_EDIT]       VARCHAR (100)  NULL,
    [EXPORT_TYPE]            VARCHAR (20)   NULL,
    [AFTER_ELEMENT]          VARCHAR (100)  NULL,
    [EDIT_LABEL_TIP]         VARCHAR (400)  NULL,
    [EDIT_NOT_SAVE]          VARCHAR (400)  NULL,
    [MEMO]                   VARCHAR (4000) NULL,
    [AUTO_UPPER]             VARCHAR (1)    NULL,
    [BATCH_EDIT]             INT            NULL,
    [LANG_CODE]              VARCHAR (100)  NULL,
    [QUERY_LOCK]             VARCHAR (100)  NULL,
    CONSTRAINT [PK_ECI_TABLE_ELEMENT] PRIMARY KEY CLUSTERED ([GUID] ASC)
);

