CREATE TABLE [dbo].[ECI_UI_CONFIG_HEAD] (
    [ID]              VARCHAR (50) NOT NULL,
    [CONFIG_CODE]     VARCHAR (50) NOT NULL,
    [PAGE_SIZE]       INT          NULL,
    [SORT_EXPRESSION] VARCHAR (50) NULL,
    [COMPANY_CODE]    VARCHAR (50) NOT NULL,
    [COMPANY_NAME]    VARCHAR (50) NULL,
    [CREATE_USER]     VARCHAR (50) NOT NULL,
    [CREATE_DATE]     DATETIME     NOT NULL
);

