CREATE TABLE [dbo].[ECI_DIC_HEAD_COM] (
    [ID]           VARCHAR (50)  NOT NULL,
    [CODE]         VARCHAR (50)  NOT NULL,
    [CREATE_USER]  VARCHAR (50)  NOT NULL,
    [CREATE_DATE]  DATETIME      NOT NULL,
    [COMPANY_CODE] VARCHAR (50)  NOT NULL,
    [COMPANY_NAME] VARCHAR (100) NULL
);

