CREATE TABLE [dbo].[ECI_COM_PARAM_INSTANCE] (
    [ID]          VARCHAR (36)   NOT NULL,
    [PARAM_ID]    VARCHAR (50)   NOT NULL,
    [INSTANCE_ID] VARCHAR (50)   NOT NULL,
    [PARAM_KEY]   VARCHAR (200)  NULL,
    [PARAM_NAME]  VARCHAR (200)  NULL,
    [PARAM_VALUE] VARCHAR (2000) NULL,
    [MEMO]        VARCHAR (200)  NULL
);

