CREATE TABLE [dbo].[ECI_TABLE] (
    [TABLE_NAME]            VARCHAR (400)  NULL,
    [MAIN_ALIAS]            VARCHAR (400)  NULL,
    [GUID]                  VARCHAR (72)   NOT NULL,
    [CREATE_DATE]           DATETIME       NULL,
    [TABLE_WIDTH]           VARCHAR (200)  NULL,
    [CONDITION]             VARCHAR (400)  NULL,
    [COLUMN_COUNT]          INT            NULL,
    [ADVANCE_CONFIG]        VARCHAR (400)  NULL,
    [CODE]                  VARCHAR (400)  NOT NULL,
    [DEFAULT_CONDITION]     VARCHAR (2000) NULL,
    [LOAD_DATA]             INT            NULL,
    [FUNCTION_ADD]          INT            NULL,
    [FUNCTION_DELETE]       INT            NULL,
    [FUNCTION_EXCEL]        INT            NULL,
    [FUNCTION_EDIT]         INT            NULL,
    [DEFAULT_SORT]          VARCHAR (400)  NULL,
    [JS_FILE]               VARCHAR (400)  NULL,
    [GRID_SQL]              VARCHAR (4000) NULL,
    [TYPE]                  VARCHAR (200)  NULL,
    [DEFAULT_PAGE_SIZE]     INT            NULL,
    [STYLE_FILE]            VARCHAR (200)  NULL,
    [FUNCTION_BACK]         INT            NULL,
    [REMARKS]               VARCHAR (2000) NULL,
    [QUERY_COLUMN_COUNT]    INT            NULL,
    [PARAM]                 VARCHAR (100)  NULL,
    [JS_SCRIPT]             VARCHAR (4000) NULL,
    [DEFAULT_SELECT]        VARCHAR (1)    NULL,
    [GRID_LAYOUT]           VARCHAR (400)  NULL,
    [KEEP_ADD_STATUS]       VARCHAR (400)  NULL,
    [ADD_SEQ]               VARCHAR (400)  NULL,
    [FILE_UPLOAD]           VARCHAR (400)  NULL,
    [UPDATE_DATE]           DATETIME       NULL,
    [PL_VERSION]            VARCHAR (100)  NULL,
    [PL_SAVE_FIXED]         VARCHAR (400)  NULL,
    [EDIT_FUNCTION_SAVE]    INT            NULL,
    [EDIT_FUNCTION_COPY]    INT            NULL,
    [EDIT_FUNCTION_CLOSE]   INT            NULL,
    [HAS_DATA_SOURCE]       VARCHAR (200)  NULL,
    [PRIMARY_KEY_INPUT]     VARCHAR (1)    NULL,
    [CREATE_USER]           VARCHAR (100)  NULL,
    [UPDATE_USER]           VARCHAR (100)  NULL,
    [DATA_SOURCE]           VARCHAR (1000) NULL,
    [SHARE_CONFIG]          VARCHAR (1000) NULL,
    [EDIT_FUNCTION_ADD]     INT            NULL,
    [FUNCTION_SAVE_BACK]    INT            NULL,
    [ADVANCE_CONFIG_SERVER] VARCHAR (200)  NULL,
    [LANG_CODE]             VARCHAR (100)  NULL,
    [CAN_CONFIG]            VARCHAR (10)   NULL,
    CONSTRAINT [PK_ECI_TABLE] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [UK_ECI_TABLE] UNIQUE NONCLUSTERED ([GUID] ASC)
);

