CREATE TABLE [dbo].[ECI_TABLE_GROUP] (
    [GUID]         VARCHAR (200)  NOT NULL,
    [DISPLAY_TYPE] VARCHAR (200)  NULL,
    [COLUMN_COUNT] INT            NULL,
    [SEQ]          INT            NULL,
    [MEMO]         VARCHAR (2000) NULL,
    [GROUP_CODE]   VARCHAR (200)  NULL,
    [GROUP_NAME]   VARCHAR (200)  NULL,
    [TABLE_GUID]   VARCHAR (100)  NOT NULL,
    CONSTRAINT [PK_ECI_TABLE_GROUP] PRIMARY KEY CLUSTERED ([GUID] ASC)
);

