CREATE TABLE [dbo].[ECI_DIC_HEAD] (
    [ID]          VARCHAR (50)  NOT NULL,
    [CODE]        VARCHAR (50)  NOT NULL,
    [NAME]        VARCHAR (50)  NOT NULL,
    [MEMO]        VARCHAR (500) NULL,
    [CREATE_USER] VARCHAR (50)  NOT NULL,
    [CREATE_DATE] DATETIME      NOT NULL,
    [UPDATE_USER] VARCHAR (50)  NOT NULL,
    [UPDATE_DATE] DATETIME      NOT NULL,
    [TABLE_NAME]  VARCHAR (50)  NULL
);

