CREATE TABLE [dbo].[ECI_TABLE_TABITEM] (
    [GUID]         VARCHAR (200)  NOT NULL,
    [TABLE_GUID]   VARCHAR (100)  NOT NULL,
    [TAB_NAME]     VARCHAR (100)  NULL,
    [SEQ]          INT            NULL,
    [STATUS]       VARCHAR (1)    NULL,
    [MEMO]         VARCHAR (4000) NULL,
    [CONTROL_ID]   VARCHAR (100)  NULL,
    [CONTROL_PATH] VARCHAR (400)  NULL,
    [SHOW_MODE]    VARCHAR (100)  NULL,
    CONSTRAINT [PK_ECI_TABLE_TABITEM] PRIMARY KEY CLUSTERED ([GUID] ASC)
);

