CREATE TABLE [dbo].[HELP_CATALOG] (
  [ID] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NOT NULL,
  [NAME] nvarchar(36) COLLATE Chinese_PRC_CI_AS  NOT NULL,
  [CODE] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
  [PARENTID] nvarchar(36) COLLATE Chinese_PRC_CI_AS  NOT NULL,
  [SEQUENCE] float(53)  NULL,
  [STATUS] char(1) COLLATE Chinese_PRC_CI_AS  NULL,
  [CREATE_USER] nvarchar(20) COLLATE Chinese_PRC_CI_AS  NULL,
  [CREATE_DATE] datetime  NULL,
  [UPDATE_USER] nvarchar(20) COLLATE Chinese_PRC_CI_AS  NULL,
  [UPDATE_DATE] datetime  NULL,
  [FCODE] nvarchar(2000) COLLATE Chinese_PRC_CI_AS  NULL,
  [FNAME] nvarchar(2000) COLLATE Chinese_PRC_CI_AS  NULL,
  [IS_HELP] char(1) COLLATE Chinese_PRC_CI_AS DEFAULT ('Y') NULL,
  [IS_ETIP] char(1) COLLATE Chinese_PRC_CI_AS DEFAULT ('Y') NULL,
  CONSTRAINT [PK_ECI_HELP_CATALOG] PRIMARY KEY CLUSTERED ([ID])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)  
ON [PRIMARY]
)  
ON [PRIMARY]
GO

ALTER TABLE [dbo].[HELP_CATALOG] SET (LOCK_ESCALATION = TABLE)