CREATE TABLE [dbo].[HELP_INFO] (
  [GUID] nvarchar(36) COLLATE Chinese_PRC_CI_AS  NULL,
  [CODE] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [TITLE] nvarchar(200) COLLATE Chinese_PRC_CI_AS  NULL,
  [BODY] text COLLATE Chinese_PRC_CI_AS  NULL,
  [CREATE_DATE] datetime  NULL,
  [CREATE_USER] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [UPDATE_DATE] datetime  NULL,
  [UPDATE_USER] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [CATALOG_ID] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [SYS_CODE] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [READ_COUNT] int DEFAULT ((0)) NOT NULL,
  CONSTRAINT [FK_ECI_HELP] FOREIGN KEY ([CATALOG_ID]) REFERENCES [dbo].[HELP_CATALOG] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
)  
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[HELP_INFO] SET (LOCK_ESCALATION = TABLE)