CREATE TABLE [dbo].[SSO_NODE_EXT] (
    [NODEID]           VARCHAR (36)  NOT NULL,
    [ATIFICIAL_PERSON] VARCHAR (255) NULL,
    [BUSINESS_LICENSE] VARCHAR (255) NULL,
    [BIZ_LIC_FILE]     VARCHAR (255) NULL,
    [ADDRESS]          VARCHAR (255) NULL,
    [ZIP]              VARCHAR (255) NULL,
    CONSTRAINT [PK_SSO_NODE_EXT] PRIMARY KEY CLUSTERED ([NODEID] ASC)
);

