CREATE TABLE [dbo].[SSO_ENTITY2ROLE] (
    [ENTITYTYPE] NVARCHAR (1)  NOT NULL,
    [ENTITYID]   NVARCHAR (36) NOT NULL,
    [ROLEID]     NVARCHAR (36) NOT NULL,
    [CREATEUSER] NVARCHAR (36) NULL,
    [CREATETIME] DATETIME      NULL,
    CONSTRAINT [PK_SSO_ENTITY2ROLE] PRIMARY KEY CLUSTERED ([ENTITYTYPE] ASC, [ENTITYID] ASC, [ROLEID] ASC)
);

