CREATE TABLE [dbo].[SSO_ENTITY2FUNC2NODE] (
    [ENTITYTYPE]   CHAR (1)      NOT NULL,
    [ENTITYID]     VARCHAR (36)  NOT NULL,
    [FUNCTIONCODE] VARCHAR (255) NOT NULL,
    [NODEID]       VARCHAR (36)  NOT NULL,
    [CREATEUSER]   VARCHAR (36)  NULL,
    [CREATETIME]   DATETIME      NULL,
    CONSTRAINT [PK_SSO_ENTITY2FUNCTION2NODE] PRIMARY KEY CLUSTERED ([ENTITYTYPE] ASC, [ENTITYID] ASC, [FUNCTIONCODE] ASC, [NODEID] ASC)
);

