CREATE TABLE [dbo].[SSO_USER2USERGROUP] (
    [USERID]      VARCHAR (36) NOT NULL,
    [USERGROUPID] VARCHAR (36) NOT NULL,
    [CREATEUSER]  VARCHAR (36) NULL,
    [CREATETIME]  DATETIME     NULL,
    CONSTRAINT [PK_SSO_USER2USERGROUP] PRIMARY KEY CLUSTERED ([USERID] ASC, [USERGROUPID] ASC)
);

