CREATE TABLE [dbo].[SSO_USERGROUP] (
    [USERGROUPID]    VARCHAR (36)  NOT NULL,
    [NAME]           VARCHAR (255) NOT NULL,
    [DESCRIPTION]    VARCHAR (255) NULL,
    [CREATEUSER]     VARCHAR (36)  NULL,
    [CREATETIME]     DATETIME      NULL,
    [LASTMODIFYUSER] VARCHAR (36)  NULL,
    [LASTMODIFYTIME] DATETIME      NULL,
    [NODEID]         VARCHAR (36)  NULL,
    [TYPE]           INT           NULL,
    CONSTRAINT [PK_SSO_USERGROUP] PRIMARY KEY CLUSTERED ([USERGROUPID] ASC)
);

