CREATE TABLE [dbo].[SSO_USER_ROLE_NODE] (
    [USERID]     NVARCHAR (36) NULL,
    [ROLEID]     NVARCHAR (36) NULL,
    [NODEID]     NVARCHAR (36) NULL,
    [CREATEUSER] NVARCHAR (36) NULL,
    [CREATETIME] DATE          NULL,
    [GUID]       NVARCHAR (36) NULL
);

