CREATE TABLE [dbo].[SSO_TOKEN] (
    [TOKEN]      VARCHAR (36) NOT NULL,
    [USERID]     VARCHAR (36) NOT NULL,
    [CREATETIME] DATETIME     NULL,
    CONSTRAINT [PK_SSO_TOKEN] PRIMARY KEY CLUSTERED ([TOKEN] ASC)
);

