CREATE TABLE [dbo].[SSO_ENTITY2FUNC] (
    [ENTITYTYPE]   NVARCHAR (1)   NOT NULL,
    [ENTITYID]     NVARCHAR (36)  NOT NULL,
    [FUNCTIONCODE] NVARCHAR (255) NOT NULL,
    [CREATEUSER]   NVARCHAR (36)  NULL,
    [CREATETIME]   DATETIME       NULL,
    CONSTRAINT [PK_SSO_ENTITY2FUNC] PRIMARY KEY CLUSTERED ([ENTITYTYPE] ASC, [ENTITYID] ASC, [FUNCTIONCODE] ASC)
);

