CREATE TABLE [dbo].[SSO_AGENCY] (
    [AGENCYID]       VARCHAR (36) NOT NULL,
    [CLIENTID]       VARCHAR (36) NOT NULL,
    [AGENTID]        VARCHAR (36) NOT NULL,
    [BEGINTIME]      DATETIME     NULL,
    [ENDTIME]        DATETIME     NULL,
    [CREATEUSER]     VARCHAR (36) NULL,
    [CREATETIME]     DATETIME     NULL,
    [LASTMODIFYUSER] VARCHAR (36) NULL,
    [LASTMODIFYTIME] DATETIME     NULL,
    CONSTRAINT [PK_SSO_AGENT] PRIMARY KEY CLUSTERED ([AGENCYID] ASC)
);

