CREATE TABLE [dbo].[SSO_USER_EXT] (
    [USERID]    VARCHAR (36) NOT NULL,
    [ID_TYPE]   INT          NULL,
    [ID_NUMBER] VARCHAR (20) NULL,
    CONSTRAINT [PK_SSO_USER_EXT] PRIMARY KEY CLUSTERED ([USERID] ASC)
);

